"""
evaluate.py
-----------
Evaluates the quality of synthetic tabular data generated by a Binary Diffusion model.

Protocol (following the paper):
  - Downstream models: Logistic/Linear Regression (LR), Decision Tree (DT), Random Forest (RF)
  - Metric: accuracy (classification) or MSE (regression)
  - 5 synthetic training sets → report mean ± std

Usage:
    python evaluate.py --config config.yaml
"""

import argparse
import yaml
import numpy as np
import pandas as pd

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.preprocessing import OrdinalEncoder, LabelEncoder
from sklearn.metrics import accuracy_score, mean_squared_error


# ── Paper hyperparameters (Table 2) ───────────────────────────────────────────
# Keys match the `dataset_name` field in the config (case-insensitive).
# California Housing is a regression task → LR = LinearRegression (no max_iter).
DATASET_HYPERPARAMS = {
    "travel":     {"lr_max_iter": 100,  "dt_max_depth": 6,  "rf_max_depth": 12, "rf_n_estimators": 75},
    "sick":       {"lr_max_iter": 200,  "dt_max_depth": 10, "rf_max_depth": 12, "rf_n_estimators": 90},
    "heloc":      {"lr_max_iter": 500,  "dt_max_depth": 6,  "rf_max_depth": 12, "rf_n_estimators": 78},
    "adult":      {"lr_max_iter": 1000, "dt_max_depth": 8,  "rf_max_depth": 12, "rf_n_estimators": 85},
    "diabetes":   {"lr_max_iter": 500,  "dt_max_depth": 10, "rf_max_depth": 20, "rf_n_estimators": 120},
    "california": {"lr_max_iter": None, "dt_max_depth": 10, "rf_max_depth": 12, "rf_n_estimators": 85},
}


# ── I/O helpers ───────────────────────────────────────────────────────────────

def load_config(config_path: str) -> dict:
    """Load and return the YAML configuration file."""
    with open(config_path) as f:
        return yaml.safe_load(f)


def load_csv(path: str) -> pd.DataFrame:
    """Load a CSV file, replacing '?' with NaN (common missing-value marker)."""
    return pd.read_csv(path, na_values=["?"])


# ── Preprocessing ─────────────────────────────────────────────────────────────

def _fill_nan(df: pd.DataFrame, data_cfg: dict) -> pd.DataFrame:
    """Fill NaN: mean for numerical columns, mode for categorical columns."""
    for col in data_cfg.get("numerical_columns") or []:
        if col in df.columns:
            col_mean = df[col].mean()
            df[col] = df[col].fillna(col_mean if pd.notna(col_mean) else 0)
    for col in data_cfg.get("categorical_columns") or []:
        if col in df.columns:
            mode = df[col].mode()
            df[col] = df[col].fillna(mode[0] if len(mode) > 0 else "unknown")
    return df


def preprocess(df: pd.DataFrame, data_cfg: dict) -> pd.DataFrame:
    """
    Apply column dropping and NaN handling for REAL data as specified in config.

    Parameters
    ----------
    df       : raw DataFrame
    data_cfg : the `data` section of the config dict
    """
    cols_to_drop = data_cfg.get("columns_to_drop") or []
    df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

    if data_cfg.get("dropna"):
        df = df.dropna()
    elif data_cfg.get("fillna"):
        df = _fill_nan(df, data_cfg)

    return df.reset_index(drop=True)


def preprocess_synthetic(df: pd.DataFrame, data_cfg: dict) -> pd.DataFrame:
    """
    Apply column dropping and NaN handling for SYNTHETIC data.

    Generated data may contain residual NaN values; we always fill them
    rather than dropping rows (dropping would discard generated samples).

    Parameters
    ----------
    df       : raw synthetic DataFrame
    data_cfg : the `data` section of the config dict
    """
    cols_to_drop = data_cfg.get("columns_to_drop") or []
    df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

    nan_count = df.isna().sum().sum()
    if nan_count > 0:
        print(f"    ⚠  {nan_count} NaN(s) found in synthetic data — filling instead of dropping.")
        df = _fill_nan(df, data_cfg)

    return df.reset_index(drop=True)


def split_X_y(df: pd.DataFrame, target_col: str):
    """Split a DataFrame into feature matrix X and target series y."""
    return df.drop(columns=[target_col]), df[target_col]


def fit_encode_features(X_train: pd.DataFrame, X_test: pd.DataFrame,
                        categorical_cols: list):
    """
    Ordinal-encode categorical columns.
    Encoder is fitted on X_train and applied to both splits.

    Returns numpy arrays (X_train_enc, X_test_enc).
    """
    cat_present = [c for c in (categorical_cols or []) if c in X_train.columns]

    X_train = X_train.copy()
    X_test  = X_test.copy()

    if cat_present:
        enc = OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1)
        X_train[cat_present] = enc.fit_transform(X_train[cat_present].astype(str))
        X_test[cat_present]  = enc.transform(X_test[cat_present].astype(str))

    return X_train.values.astype(float), X_test.values.astype(float)


def encode_target(y_train: pd.Series, y_test: pd.Series, task: str):
    """
    Label-encode target for classification; cast to float for regression.
    Encoder is fitted on y_train and applied to y_test.
    """
    if task == "classification":
        le = LabelEncoder()
        y_train_enc = le.fit_transform(y_train.astype(str))
        y_test_enc  = le.transform(y_test.astype(str))
    else:
        y_train_enc = y_train.values.astype(float)
        y_test_enc  = y_test.values.astype(float)
    return y_train_enc, y_test_enc


# ── Model factory ─────────────────────────────────────────────────────────────

def build_models(task: str, hp: dict) -> dict:
    """
    Instantiate LR, DT, RF with dataset-specific hyperparameters.

    Parameters
    ----------
    task : 'classification' or 'regression'
    hp   : hyperparameter dict from DATASET_HYPERPARAMS
    """
    if task == "classification":
        return {
            "LR": LogisticRegression(
                max_iter=hp["lr_max_iter"], n_jobs=-1, random_state=42
            ),
            "DT": DecisionTreeClassifier(
                max_depth=hp["dt_max_depth"], random_state=42
            ),
            "RF": RandomForestClassifier(
                max_depth=hp["rf_max_depth"],
                n_estimators=hp["rf_n_estimators"],
                n_jobs=-1, random_state=42
            ),
        }
    else:  # regression
        return {
            "LR": LinearRegression(n_jobs=-1),
            "DT": DecisionTreeRegressor(
                max_depth=hp["dt_max_depth"], random_state=42
            ),
            "RF": RandomForestRegressor(
                max_depth=hp["rf_max_depth"],
                n_estimators=hp["rf_n_estimators"],
                n_jobs=-1, random_state=42
            ),
        }


# ── Evaluation ────────────────────────────────────────────────────────────────

def score_model(model, X_train, y_train, X_test, y_test, task: str) -> float:
    """Train `model` on synthetic data and return metric on real test data."""
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    if task == "classification":
        return accuracy_score(y_test, y_pred)
    else:
        return mean_squared_error(y_test, y_pred)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Evaluate Binary Diffusion synthetic data via downstream ML models."
    )
    parser.add_argument("--config", required=True, help="Path to YAML config file.")
    args = parser.parse_args()

    # ── Load config ───────────────────────────────────────────────────────────
    cfg      = load_config(args.config)
    data_cfg = cfg["data"]

    dataset_name = cfg["dataset_name"].lower()
    task         = data_cfg["task"]                # 'classification' or 'regression'
    target_col   = data_cfg.get("target_column")   # None → no supervised evaluation
    cat_cols     = data_cfg.get("categorical_columns") or []

    assert dataset_name in DATASET_HYPERPARAMS, (
        f"Unknown dataset '{dataset_name}'. "
        f"Choose from: {list(DATASET_HYPERPARAMS.keys())}"
    )
    hp = DATASET_HYPERPARAMS[dataset_name]

    # ── Load & preprocess real test data ──────────────────────────────────────
    test_df = load_csv(cfg["path_test"])
    test_df = preprocess(test_df, data_cfg)

    if target_col and target_col in test_df.columns:
        X_test_raw, y_test_raw = split_X_y(test_df, target_col)
    else:
        raise ValueError(
            f"Target column '{target_col}' not found in test data. "
            "Cannot perform supervised evaluation."
        )

    # ── Evaluate over each synthetic dataset ──────────────────────────────────
    synthetic_paths = cfg["path_synthetic_trains"]
    # Accumulate per-model scores across the N synthetic datasets
    scores = {model_name: [] for model_name in ["LR", "DT", "RF"]}

    for i, syn_path in enumerate(synthetic_paths, 1):
        print(f"  [run {i}/{len(synthetic_paths)}] Loading {syn_path} ...")

        syn_df = load_csv(syn_path)
        syn_df = preprocess_synthetic(syn_df, data_cfg)

        # For conditional generation, synthetic data contains the target column.
        # For unconditional generation, all columns are present (incl. target).
        # Either way, we extract X and y the same way.
        if target_col and target_col in syn_df.columns:
            X_syn_raw, y_syn_raw = split_X_y(syn_df, target_col)
        else:
            raise ValueError(
                f"Target column '{target_col}' not found in synthetic file '{syn_path}'."
            )

        # Encode features (fit on synthetic train, apply to real test)
        X_train_enc, X_test_enc = fit_encode_features(X_syn_raw, X_test_raw, cat_cols)
        y_train_enc, y_test_enc = encode_target(y_syn_raw, y_test_raw, task)

        models = build_models(task, hp)
        for name, model in models.items():
            s = score_model(model, X_train_enc, y_train_enc,
                            X_test_enc, y_test_enc, task)
            scores[name].append(s)

    # ── Report results ────────────────────────────────────────────────────────
    metric_label = "Accuracy ↑" if task == "classification" else "MSE ↓"
    header = f"Dataset: {dataset_name.upper()} | Task: {task} | Metric: {metric_label}"

    print(f"\n{'=' * 60}")
    print(header)
    print(f"{'=' * 60}")
    print(f"{'Model':<8}  {'Mean':>10}  {'Std':>10}  {'All scores'}")
    print(f"{'-' * 60}")
    for model_name, run_scores in scores.items():
        mean = np.mean(run_scores)
        std  = np.std(run_scores)
        all_s = "  ".join(f"{s:.4f}" for s in run_scores)
        print(f"{model_name:<8}  {mean:>10.4f}  {std:>10.4f}  [{all_s}]")
    print(f"{'=' * 60}\n")


if __name__ == "__main__":
    main()
